#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/c5f55550-8d61-424a-9301-25d14b0fd50f
title: dataWeave-operators
description: This REST API is to authenticate user credentials and authorize to specified LDAP group.
version: 1.0

mediaType: [ application/json, application/xml ]

/operators:
  /map:
    get:
      responses:
        200:
          body:
            application/json:
  /mapObject:
    get:
      responses:
        200:
          body:
            application/json:
  /pluck:
    get:
      responses:
        200:
          body:
            application/json:
  /filter:
    get:
      responses:
        200:
          body:
            application/json:
  /remove:
    get:
      responses:
        200:
          body:
            application/json:
  /and:
    get:
      responses:
        200:
          body:
            application/json:
  /or:
    get:
      responses:
        200:
          body:
            application/json:
  /is:
    get:
      responses:
        200:
          body:
            application/json:
  /concat:
    get:
      responses:
        200:
          body:
            application/json:
  /contains:
    get:
      responses:
        200:
          body:
            application/json:
  /coerce:
    get:
      responses:
        200:
          body:
            application/json:
  /typeOf:
    get:
      responses:
        200:
          body:
            application/json:
  /flatten:
    get:
      responses:
        200:
          body:
            application/json:
  /sizeOf:
    get:
      responses:
        200:
          body:
            application/json:
  /arrayPush:
    get:
      responses:
        200:
          body:
            application/json:
  /arrayRemove:
    get:
      responses:
        200:
          body:
            application/json:
  /removeMatchingFromArray:
    get:
      responses:
        200:
          body:
            application/json:
  /averageOfArray:
    get:
      responses:
        200:
          body:
            application/json:
  /reduce:
    get:
      responses:
        200:
          body:
            application/json:
  /joinBy:
    get:
      responses:
        200:
          body:
            application/json:
  /splitBy:
    get:
      responses:
        200:
          body:
            application/json:
  /orderBy:
    get:
      responses:
        200:
          body:
            application/json:
  /groupBy:
    get:
      responses:
        200:
          body:
            application/json:
  /distinctBy:
    get:
      responses:
        200:
          body:
            application/json:
  /zip:
    get:
      responses:
        200:
          body:
            application/json:
  /unzip:
    get:
      responses:
        200:
          body:
            application/json:
  /replace:
    get:
      responses:
        200:
          body:
            application/json:
  /matches:
    get:
      responses:
        200:
          body:
            application/json:
  /startsWith:
    get:
      responses:
        200:
          body:
            application/json:
  /endsWith:
    get:
      responses:
        200:
          body:
            application/json:
  /find:
    get:
      responses:
        200:
          body:
            application/json:
  /match:
    get:
      responses:
        200:
          body:
            application/json:
  /scan:
    get:
      responses:
        200:
          body:
            application/json:
  /similar:
    get:
      responses:
        200:
          body:
            application/json:
  /upper:
    get:
      responses:
        200:
          body:
            application/json:
  /lower:
    get:
      responses:
        200:
          body:
            application/json:
  /camelize:
    get:
      responses:
        200:
          body:
            application/json:
  /capitalize:
    get:
      responses:
        200:
          body:
            application/json:
  /dasherize:
    get:
      responses:
        200:
          body:
            application/json:
  /underscore:
    get:
      responses:
        200:
          body:
            application/json:
  /pluralize:
    get:
      responses:
        200:
          body:
            application/json:
  /singularize:
    get:
      responses:
        200:
          body:
            application/json:
  /trim:
    get:
      responses:
        200:
          body:
            application/json:
  /substring:
    get:
      responses:
        200:
          body:
            application/json:
  /ordinalize:
    get:
      responses:
        200:
          body:
            application/json:
  /plus:
    get:
      responses:
        200:
          body:
            application/json:
  /minus:
    get:
      responses:
        200:
          body:
            application/json:
  /multiply:
    get:
      responses:
        200:
          body:
            application/json:
  /division:
    get:
      responses:
        200:
          body:
            application/json:
  /max:
    get:
      responses:
        200:
          body:
            application/json:
  /min:
    get:
      responses:
        200:
          body:
            application/json:
  /round:
    get:
      responses:
        200:
          body:
            application/json:
  /sqrt:
    get:
      responses:
        200:
          body:
            application/json:
  /pow:
    get:
      responses:
        200:
          body:
            application/json:
  /ceil:
    get:
      responses:
        200:
          body:
            application/json:
  /floor:
    get:
      responses:
        200:
          body:
            application/json:
  /abs:
    get:
      responses:
        200:
          body:
            application/json:
  /mod:
    get:
      responses:
        200:
          body:
            application/json:
  /now:
    get:
      responses:
        200:
          body:
            application/json:
  /getTimeUnit:
    get:
      responses:
        200:
          body:
            application/json:
  /shiftTimeZone:
    get:
      responses:
        200:
          body:
            application/json:
  /appendTime:
    get:
      responses:
        200:
          body:
            application/json:
  /appendTimeZone:
    get:
      responses:
        200:
          body:
            application/json:
  /addPeriodOfTime:
    get:
      responses:
        200:
          body:
            application/json:
  /subtractPeriodOfTime:
    get:
      responses:
        200:
          body:
            application/json:
  /subtractTwoDates:
    get:
      responses:
        200:
          body:
            application/json: 